# Generated by Django 4.1.7 on 2023-04-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Şəhərlər'},
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
